name: Docker Builder

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-qnn-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: docker/docker_compose_compile_and_share.sh
