name: Docker Builder

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-qnn-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Update Submodule
      run: |
        git submodule foreach --recursive git fetch
        git submodule foreach --recursive git reset --hard
        git submodule update --init --recursive --checkout
        git submodule update --recursive
    - name: Build Debug
      run: docker/docker_compose_compile_and_share.sh -r -d --print-build-time
    - name: Build Release
      run: docker/docker_compose_compile_and_share.sh -r --print-build-time
    - name: Build Linux Debug
      run: docker/docker_compose_compile_and_share.sh -r -d --print-build-time --build-linux-x64
    - name: Run test-backend-ops
      run: |
        sudo apt update && sudo apt install libc++-dev
        LD_LIBRARY_PATH='build_qnn_x86_64:$LD_LIBRARY_PATH' build_qnn_x86_64/test-backend-ops test -b qnn-cpu
